### PR TITLE
Fix typing for Order

### LINKED ISSUE #11: Error with Order
Using a simple order option like `[['createdAt', 'DESC']]` does not work:
```ts
await User.find({
    order: [['createdAt', 'DESC']]
});
```
results in
```ts
[ts] Argument of type '{ where: { [x: string]: any; [x: number]: undefined; userId: any; }; order: [string[]]; attribute...' is not assignable to parameter of type 'FindOptions'.
 Types of property 'order' are incompatible.
   Type '[string[]]' is not assignable to type 'string | fn | col | literal | [string | col | fn | literal, string] | [Model<any, any> | { model:...'.
     Type '[string[]]' is not assignable to type '(string | fn | col | literal | [string | col | fn | literal, string] | [Model<any, any> | { model...'.
       Types of property '[Symbol.iterator]' are incompatible.
         Type '() => IterableIterator<string[]>' is not assignable to type '() => IterableIterator<string | fn | col | literal | [string | col | fn | literal, string] | [Mod...'.
           Type 'IterableIterator<string[]>' is not assignable to type 'IterableIterator<string | fn | col | literal | [string | col | fn | literal, string] | [Model<any...'.
             Type 'string[]' is not assignable to type 'string | fn | col | literal | [string | col | fn | literal, string] | [Model<any, any> | { model:...'.
               Type 'string[]' is not assignable to type '[Model<any, any>, Model<any, any>, string, string]'.
                 Property '0' is missing in type 'string[]'.
```
`Order` is defined as
```ts
  export type OrderItem =
    string | fn | col | literal |
    [string | col | fn | literal, string] |
    [Model<any, any> | { model: Model<any, any>, as: string }, string, string] |
    [Model<any, any>, Model<any, any>, string, string];
  export type Order = OrderItem | OrderItem[];
```
I'm not sure why it doesn't work, any idea?

### PR DESCRIPTION
**Pull request by felixfbecker**
Fixes #11

### CODE REVIEW

File: index.d.ts [hunk 1]
```diff
@@ -2976,7 +2976,7 @@ declare module sequelize {
     [string | col | fn | literal, string] |
     [Model<any, any> | { model: Model<any, any>, as: string }, string, string] |
     [Model<any, any>, Model<any, any>, string, string];
-  export type Order = OrderItem | OrderItem[];
+  export type Order = string | fn | col | literal | OrderItem[];
```
Comment (louy) [inline index.d.ts]: You left out `OrderItem`

**Comment by louy** [comment]
It's probably worth it to use [the examples](http://docs.sequelizejs.com/en/latest/docs/querying/#ordering) in the docs in tests.

File: index.d.ts (hunk 1 above)
Comment (louy) [inline index.d.ts]: I think your intention was to add `string[]` to `OrderItem` rather than removing it here. Tests are failing in travis ci.

Comment (felixfbecker) [inline index.d.ts]: No, like I said, passing a single `OrderItem` like `['name', 'DESC']` is not valid, it would get interpreted as two columns `name` and `DESC` and fail with an column-does-no-exist-error.

File: test/test.ts [hunk 2]
```diff
@@ -11,3 +11,44 @@ var dt: Sequelize.DataTypes;
 // var dt: typeof Sequelize.DataTypes; // Should give an error. It's not a value but an interface.
 
 var i: typeof Sequelize.Instance;
+
+const Something = sequelize.define();
```
Comment (louy) [inline test/test.ts]: You'll have to give this some arguments. `sequelize.define('', {});`

File: index.d.ts (hunk 1 above)
Comment (louy) [inline index.d.ts]: Sorry I misunderstood that the first time. There's [one issue that breaks build on travis ci](https://travis-ci.org/louy/typed-sequelize/builds/138466805#L180-L182). If you can fix that I'm happy to merge this.

**Comment by felixfbecker** [comment]
Sorry, I'm currently short on time. We could work around this by casting to `OrderItem[]` and I initially hoped that this PR would allow us to omit it, but TS just cannot infer tuple types, so it doesn't really fix it :/

**Comment by louy** [comment]
No problem. I've fixed the build issue myself and merged.
Yeah I know. I always struggle with this.
